# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Example Cygnus"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["charybdis_left", "charybdis_right"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000\nCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y"]'
      modules: '["Vzhao-L/zmk-for-charybdis/Cygnus"]'
